cache:
  directories:
    - "node_modules"
language: node_js
node_js:
  - "lts/*"

services:
  - docker

before_script:
  - npm install

script:
  - npm test

deploy:
  provider: azure_web_apps
  verbose: true

after_deploy:
  - docker build -t jmadoremos/tbs-chatroom -f ./Dockerfile .
  - docker tag jmadoremos/tbs-chatroom jmadoremos/tbs-chatroom:$(git rev-parse --short HEAD);
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  - docker push jmadoremos/tbs-chatroom;
